### ISSUE TITLE
Add benefits from UKMOD

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-uk#8]
UKMOD has many more benefits to use, which we should aim to implement, including:

- [x] Jobseeker’s Allowance (contributory)
- [x] Jobseeker’s Allowance (income-based)
- [x] Employment Support Allowance + Incapacity Benefit (contributory)
- [x] Employment Support Allowance (income based)
- [x] Basic State Retirement Pension
- [ ] Earnings related state pension
- [x] Pension Credit
- [x] Winter Fuel Allowance
- [x] Bereavement Benefit
- [ ] Maternity Allowance
- [x] Statutory Sick Pay
- [x] Statutory Maternity/Paternity Pay
- [x] Attendance Allowance
- [x] Disability Living Allowance
- [x] Personal Independence Payment
- [x] Severe Disablement Allowance
- [x] Carers Allowance
- [x] Industrial Injuries Disablement Benefit
- [ ] War Pension
- [x] Child Benefit
- [x] Child Tax Credit
- [x] Working Tax Credit
- [x] Income Support
- [x] Housing Benefit
- [x] Local Housing Allowance
- [x] Universal Credit
- [ ] Council Tax Benefit
- [ ] Educational Maintenance Allowance
- [ ] Sure Start Maternity Grant
- [x] Benefit cap

**Comment by MaxGhenis** [comment]
Is this complete? If not want to make it a checklist?

**Comment by nikhilwoodruff** [comment]
Yep, that's a better idea, there's still some (e.g. bereavement benefit) that we don't model

**Comment by MaxGhenis** [comment]
I'd suggest we split out the remaining checkboxes into separate issues.

**Comment by MaxGhenis** [comment]
I've made separate issues/epics for the remaining tasks, and converted this to an epic.

**Comment by nikhilwoodruff** [comment]
Closing since we match reporting level with UKMOD.
